### ISSUE TITLE
Make 'ember-vcl-l10n-props-support' optional

### ISSUE THREAD

**Issue by Dani723** [ember-vcl/password-input#1]
An exception is thrown in the `ember-vcl-l10n-props-support dependency`, when using the component without Ember I18n.

`Uncaught TypeError: Cannot read property 'exists' of undefined`

![image](https://cloud.githubusercontent.com/assets/3123390/7931541/c1c8fdee-0911-11e5-9c06-d267310eb3af.png)

**Comment by vanthome** [comment]
Should be solved by now
